name: Melon Ticket Monitoring

on:
  workflow_dispatch: 
  schedule:
    - cron: '*/5 * * * *' 

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    strategy:
      # Matrix 矩陣設定：讓三個場次並行跑
      matrix:
        schedule: ['100001', '100002', '100003'] # 👈 請把這三個換成你查到的三場 ID 數字！
        
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Melon Ticket Monitor Action
        uses: ./
        with:
          product-id: '213277'
          schedule-id: ${{ matrix.schedule }} # 👈 這裡會自動代入上面矩陣中的每一場 ID
          slack-incoming-webhook-url: ${{ secrets.NOTIFIER_HOOK_URL }}
