name: Melon Ticket Monitoring

on:
  workflow_dispatch: # 保持手動按鈕
  schedule:
    - cron: '*/5 * * * *' # 每 5 分鐘自動跑一次

jobs:
  check-tickets:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Melon Ticket Monitor Action
        uses: ./
        with:
          # 這裡必須精準使用作者指定的變數名稱：
          product-id: '213277' # 直接把你的演唱會 ID 寫在這裡！
          slack-incoming-webhook-url: ${{ secrets.NOTIFIER_HOOK_URL }} # 帶入你的 Discord 網址
